### ISSUE TITLE
shibsp::ListenerException after reboot

### ISSUE THREAD

**Issue by michzimny** [up2university/selcont#1]
Each time (tested many times) after VM reboots, SeLCont URL responds with:
```
shibsp::ListenerException
The system encountered an error at Mon Mar 26 15:06:33 2018 To report this problem, please contact the site administrator at root@localhost.
Please include the following message in any email:
shibsp::ListenerException at (https://selcont.test.up2university.eu/)
Cannot connect to shibd process, a site adminstrator should be notified. 
```

Each time, I need just to log in to VM and call:
```
sudo systemctl restart shibd
```

And then it get back to work.

My feeling is that the order of starting system deamons at the boot time is somehow not fine. It seems that shibd should be started at the end, and it might solve the issue. 

Yes, this is minor...

**Comment by Dimitrispant** [comment]
@michzimny I'm currently testing this issue on the testing instance. I will inform you when it's done.

**Comment by Dimitrispant** [comment]
@michzimny I made a change on shibd.service on systemd, so it will start after httpd.service. I made this change on the test and on the production instance and now I think is fine.

**Comment by michzimny** [comment]
Ok, thanks.

**Comment by michzimny** [comment]
I just restarted both VMs. 
https://selcont.test.up2university.eu/ - the issue persists.
https://selcont.up2university.eu/ - it's fine.

**Comment by michzimny** [comment]
Just did `systemctl restart shibd` manually to fix the issue for the test instance.

**Comment by Dimitrispant** [comment]
@michzimny I will check again the test instance

**Comment by Dimitrispant** [comment]
@michzimny I made some changes on the test instance on httpd.service and shibd.service. Can you check now?

**Comment by michzimny** [comment]
Rebooted and it's still the same. You can check it on your own making simply `sudo reboot`.

**Comment by Dimitrispant** [comment]
@michzimny I will check it. thanks!

**Comment by Dimitrispant** [comment]
@michzimny Now it's fine! I think that shibd.service was cached with the previous configuration
