### ISSUE TITLE
Web analytics

### ISSUE THREAD

**Issue by michzimny** [up2university/selcont#4]
Please add Matomo tracking code to all pages as documented here:
https://wiki.geant.org/display/UP2U/Web+Analytics

**Comment by Dimitrispant** [comment]
The tracking codes have been added on both instances

**Comment by michzimny** [comment]
It seems the code is not present in the test instance.

**Comment by Dimitrispant** [comment]
@michzimny It was not present on the frontpage but on the instances it was present. It was caused by the child theme, but now is fine.
